export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SET_USERINFO = 'SET_USERINFO'
export const SET_USERTOKEN = 'SET_USERTOKEN'
export const EDIT_PAGEDATA = 'EDIT_PAGEDATA'
export const EMPTY_PAGEDATA = 'EMPTY_PAGEDATA'
export const SET_VERSIONINFO = 'SET_VERSIONINFO'

